Repository VertaAI/modeldb, pull requests merged in 2022-09, with the labels that each got.

#3175 Fix liquibase path after liquibase version upgrade
  backend/common/src/main/java/ai/verta/modeldb/common/CommonDBUtil.java
  backend/src/main/java/ai/verta/modeldb/utils/ModelDBHibernateUtil.java
  backend/src/main/resources/liquibase/create-index-changelog.xml
  backend/src/main/resources/liquibase/create-tables-changelog-1.0.xml
  backend/src/main/resources/liquibase/create-versioning-tables-changelog.xml
  backend/src/main/resources/liquibase/create-versioning-tables-changelog2.xml
  backend/src/main/resources/liquibase/db-changelog-1.0.xml
  backend/src/main/resources/liquibase/db-changelog-2.0.xml
  backend/src/main/resources/liquibase/db-changelog-master.xml
Labels: enhancement, backend

#3192 chore: remove jakarta.el dependency management
  backend/common/pom.xml
  pom.xml
Labels: dependencies, java

#3191 chore: remove tomcat-embed-core from dependency management
  backend/common/pom.xml
  pom.xml
Labels: dependencies, java

#3153 [VUMM-297] Move artifact store to common module
  backend/common/pom.xml
  backend/common/src/main/java/ai/verta/modeldb/common/CommonConstants.java
  backend/common/src/main/java/ai/verta/modeldb/common/CommonMessages.java
  backend/common/src/main/java/ai/verta/modeldb/common/CommonUtils.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/ArtifactStoreDAO.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/ArtifactStoreDAODisabled.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/ArtifactStoreDAORdbImpl.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/ArtifactStoreService.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/NoopArtifactStoreService.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/nfs/FileStorageProperties.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/nfs/NFSController.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/nfs/NFSService.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/nfs/UploadFileResponse.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/RefCountedS3Client.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/S3Client.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/S3Controller.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/S3Service.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/S3SignatureUtil.java
  backend/common/src/main/java/ai/verta/modeldb/common/artifactStore/storageservice/s3/SignOverrideS3Signer.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/ArtifactStoreConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/Config.java
  backend/common/src/main/java/ai/verta/modeldb/common/configuration/ArtifactStoreInitBeans.java
  backend/src/main/java/ai/verta/modeldb/DAOSet.java
  backend/src/main/java/ai/verta/modeldb/ModelDBConstants.java
  backend/src/main/java/ai/verta/modeldb/ModelDBMessages.java
  backend/src/main/java/ai/verta/modeldb/ServiceSet.java
  backend/src/main/java/ai/verta/modeldb/config/MDBArtifactStoreConfig.java
  backend/src/main/java/ai/verta/modeldb/config/MDBConfig.java
  backend/src/main/java/ai/verta/modeldb/config/TestConfig.java
  backend/src/main/java/ai/verta/modeldb/configuration/AppConfigBeans.java
  backend/src/main/java/ai/verta/modeldb/configuration/CronJobUtils.java
  backend/src/main/java/ai/verta/modeldb/cron_jobs/PopulateEnvironmentInRunCron.java
  backend/src/main/java/ai/verta/modeldb/datasetVersion/DatasetVersionServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/entities/ArtifactEntity.java
  backend/src/main/java/ai/verta/modeldb/experimentRun/ExperimentRunDAORdbImpl.java
  backend/src/main/java/ai/verta/modeldb/experimentRun/FutureExperimentRunDAO.java
  backend/src/main/java/ai/verta/modeldb/experimentRun/subtypes/ArtifactHandler.java
  backend/src/main/java/ai/verta/modeldb/experimentRun/subtypes/DatasetHandler.java
  backend/src/main/java/ai/verta/modeldb/project/FutureProjectDAO.java
  backend/src/main/java/ai/verta/modeldb/versioning/BlobDAO.java
  backend/src/main/java/ai/verta/modeldb/versioning/BlobDAORdbImpl.java
  backend/src/main/java/ai/verta/modeldb/versioning/VersioningServiceImpl.java
  backend/src/test/java/ai/verta/modeldb/CommitTest.java
  backend/src/test/java/ai/verta/modeldb/DatasetTest.java
  backend/src/test/java/ai/verta/modeldb/DatasetVersionTest.java
  backend/src/test/java/ai/verta/modeldb/ExperimentRunTest.java
  backend/src/test/java/ai/verta/modeldb/ExperimentTest.java
  backend/src/test/java/ai/verta/modeldb/ProjectTest.java
  backend/src/test/java/ai/verta/modeldb/TestsInit.java
Labels: backend

#3227 Added Lombok dependency
  backend/common/pom.xml
  backend/common/src/main/java/ai/verta/modeldb/common/CommonMessages.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/ArtifactStoreConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/Config.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/CronJobConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/DatabaseConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/GrpcServerConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/NFSConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/NFSEndpointConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/RdbConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/S3Config.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/ServiceConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/ServiceUserConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/config/SpringServerConfig.java
  backend/common/src/main/java/ai/verta/modeldb/common/configuration/ArtifactStoreInitBeans.java
  backend/pom.xml
  backend/src/main/java/ai/verta/modeldb/DAOSet.java
  backend/src/main/java/ai/verta/modeldb/ServiceSet.java
  backend/src/main/java/ai/verta/modeldb/advancedService/AdvancedServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/comment/CommentServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/config/MDBConfig.java
  backend/src/main/java/ai/verta/modeldb/config/MigrationConfig.java
  backend/src/main/java/ai/verta/modeldb/config/TelemetryConfig.java
  backend/src/main/java/ai/verta/modeldb/config/TestConfig.java
  backend/src/main/java/ai/verta/modeldb/configuration/AppConfigBeans.java
  backend/src/main/java/ai/verta/modeldb/configuration/CronJobUtils.java
  backend/src/main/java/ai/verta/modeldb/configuration/Migration.java
  backend/src/main/java/ai/verta/modeldb/configuration/ReconcilerInitializer.java
  backend/src/main/java/ai/verta/modeldb/configuration/TelemetryInitBean.java
  backend/src/main/java/ai/verta/modeldb/dataset/DatasetServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/datasetVersion/DatasetVersionServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentDAO.java
  backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/experimentRun/FutureExperimentRunServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/lineage/LineageServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/metadata/MetadataServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/project/FutureProjectDAO.java
  backend/src/main/java/ai/verta/modeldb/project/FutureProjectServiceImpl.java
  backend/src/main/java/ai/verta/modeldb/versioning/VersioningServiceImpl.java
  backend/src/test/java/ai/verta/modeldb/AuthClientInterceptor.java
  backend/src/test/java/ai/verta/modeldb/TestsInit.java
  pom.xml
Labels: enhancement
